### ISSUE TITLE
Bug in azureblogstorage.js row 170

### ISSUE THREAD

**Issue by mkotamies** [Azure/node-red-contrib-azure#20]
azureblobstorage.js has typo/bug in row 170.

When downloadBlob thorws error the module crashes because of typo:
`blobservice.getBlobToLocalFile(containerName, blobName, fileName, function (error2) {
            if (error2) {
                node.log(error);
}`

Row 170 should be node.log(error2).

Path to file is node-red-contrib-azure/blob-storage/azureblobstorage.js

I can provide PR to this if you want.

**Comment by rasavant-ms** [comment]
Thanks for catching this.
Fixed now!
