### ISSUE TITLE
Empty Virtual Folders being Created in Blob Storage

### ISSUE THREAD

**Issue by drgaylord** [Azure/node-red-contrib-azure#6]
Passing a full filepath + filename as a msg.payload to the Azure Save Blob Storage node places the desired file into Azure; however, it is appending the filepath to the Storage Container Name causing the file to be placed several levels deeper in the hierarchy than desired.  It is causing the automatic addition of the unnecessary, and empty virtual folders.
 
Example:  local filepath = /home/pi/Images
                 local filename = lastimage.jpeg
                 msg.payload = "/home/pi/Images/lastimage.jpeg"
                 storage container = mystoragecontainer

As-Is the node will place the file in Azure as = /mystoragecontainer/home/pi/images/lastimage.jpeg
To-Be the node will place the file in Azure as = /mystoragecontainer/lastimage.jpeg

Azure Portal, Azure Storage Explorer, and Azure Image Explorer all do not work with the deep virtual folder structure.  Suggest that localfilepath be stripped from the localfilename before sending to Azure.

**Comment by rasavant-ms** [comment]
@drgaylord - This issue should be resolved in the v0.3.0 which is available now.
Please try it out and let me know if that solves the issue for you!
